### ISSUE TITLE
Example for Constants

### ISSUE THREAD

**Issue by deckenventilator24** [Nekos-life/neko-bot-jda#12]
Hello, could you add an example configuration for the constants?
Would be nice.

Thanks

**Comment by IamTails** [comment]
i did not see this and does not apply anymore but the config was in the file https://github.com/Nekos-life/neko-bot-jda/blob/c883d2dcc446fb5a70869196183435f8aa948de8/src/main/java/life/nekos/bot/commons/Constants.java
