### ISSUE TITLE
Database Model

### ISSUE THREAD

**Issue by ArnaudLier** [Nekos-life/neko-bot-jda#3]
Can you give me a database model for RethinkDB please?

**Comment by Andre601** [comment]
What do you mean with "database model"?

Instructions on how to install RethinkDB on your server can be found here: https://rethinkdb.com/docs/install/

**Comment by IamTails** [comment]
I am assuming he wants the structure for the database, you can manually decipher from here https://github.com/Nekos-life/neko-bot-jda/blob/master/src/main/java/life/nekos/bot/commons/db/Models.java and create your tables and fields

**Comment by IamTails** [comment]
However this really isn't an issue, and you can be better served by asking these questions in our discord server https://invite.nekos.life
